/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteTrainingRouteImport } from './routes/_site.training'
import { Route as SiteTalentStaffingRouteImport } from './routes/_site.talent-staffing'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteAboutRouteImport } from './routes/_site.about'
import { Route as SiteServicesIndexRouteImport } from './routes/_site.services.index'
import { Route as SiteExpertiseIndexRouteImport } from './routes/_site.expertise.index'
import { Route as SiteCoursesIndexRouteImport } from './routes/_site.courses.index'
import { Route as SiteServicesSlugRouteImport } from './routes/_site.services.$slug'
import { Route as SiteExpertiseSlugRouteImport } from './routes/_site.expertise.$slug'
import { Route as SiteCoursesSlugRouteImport } from './routes/_site.courses.$slug'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTrainingRoute = SiteTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTalentStaffingRoute = SiteTalentStaffingRouteImport.update({
  id: '/talent-staffing',
  path: '/talent-staffing',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteServicesIndexRoute = SiteServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteExpertiseIndexRoute = SiteExpertiseIndexRouteImport.update({
  id: '/expertise/',
  path: '/expertise/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCoursesIndexRoute = SiteCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteServicesSlugRoute = SiteServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteExpertiseSlugRoute = SiteExpertiseSlugRouteImport.update({
  id: '/expertise/$slug',
  path: '/expertise/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCoursesSlugRoute = SiteCoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/talent-staffing': typeof SiteTalentStaffingRoute
  '/training': typeof SiteTrainingRoute
  '/courses/$slug': typeof SiteCoursesSlugRoute
  '/expertise/$slug': typeof SiteExpertiseSlugRoute
  '/services/$slug': typeof SiteServicesSlugRoute
  '/courses/': typeof SiteCoursesIndexRoute
  '/expertise/': typeof SiteExpertiseIndexRoute
  '/services/': typeof SiteServicesIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/talent-staffing': typeof SiteTalentStaffingRoute
  '/training': typeof SiteTrainingRoute
  '/': typeof SiteIndexRoute
  '/courses/$slug': typeof SiteCoursesSlugRoute
  '/expertise/$slug': typeof SiteExpertiseSlugRoute
  '/services/$slug': typeof SiteServicesSlugRoute
  '/courses': typeof SiteCoursesIndexRoute
  '/expertise': typeof SiteExpertiseIndexRoute
  '/services': typeof SiteServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/_site/about': typeof SiteAboutRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/talent-staffing': typeof SiteTalentStaffingRoute
  '/_site/training': typeof SiteTrainingRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/courses/$slug': typeof SiteCoursesSlugRoute
  '/_site/expertise/$slug': typeof SiteExpertiseSlugRoute
  '/_site/services/$slug': typeof SiteServicesSlugRoute
  '/_site/courses/': typeof SiteCoursesIndexRoute
  '/_site/expertise/': typeof SiteExpertiseIndexRoute
  '/_site/services/': typeof SiteServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/talent-staffing'
    | '/training'
    | '/courses/$slug'
    | '/expertise/$slug'
    | '/services/$slug'
    | '/courses/'
    | '/expertise/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/contact'
    | '/talent-staffing'
    | '/training'
    | '/'
    | '/courses/$slug'
    | '/expertise/$slug'
    | '/services/$slug'
    | '/courses'
    | '/expertise'
    | '/services'
  id:
    | '__root__'
    | '/_site'
    | '/_site/about'
    | '/_site/contact'
    | '/_site/talent-staffing'
    | '/_site/training'
    | '/_site/'
    | '/_site/courses/$slug'
    | '/_site/expertise/$slug'
    | '/_site/services/$slug'
    | '/_site/courses/'
    | '/_site/expertise/'
    | '/_site/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/training': {
      id: '/_site/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof SiteTrainingRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/talent-staffing': {
      id: '/_site/talent-staffing'
      path: '/talent-staffing'
      fullPath: '/talent-staffing'
      preLoaderRoute: typeof SiteTalentStaffingRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/services/': {
      id: '/_site/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof SiteServicesIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/expertise/': {
      id: '/_site/expertise/'
      path: '/expertise'
      fullPath: '/expertise/'
      preLoaderRoute: typeof SiteExpertiseIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/courses/': {
      id: '/_site/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof SiteCoursesIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/services/$slug': {
      id: '/_site/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof SiteServicesSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/expertise/$slug': {
      id: '/_site/expertise/$slug'
      path: '/expertise/$slug'
      fullPath: '/expertise/$slug'
      preLoaderRoute: typeof SiteExpertiseSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/courses/$slug': {
      id: '/_site/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof SiteCoursesSlugRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteTalentStaffingRoute: typeof SiteTalentStaffingRoute
  SiteTrainingRoute: typeof SiteTrainingRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteCoursesSlugRoute: typeof SiteCoursesSlugRoute
  SiteExpertiseSlugRoute: typeof SiteExpertiseSlugRoute
  SiteServicesSlugRoute: typeof SiteServicesSlugRoute
  SiteCoursesIndexRoute: typeof SiteCoursesIndexRoute
  SiteExpertiseIndexRoute: typeof SiteExpertiseIndexRoute
  SiteServicesIndexRoute: typeof SiteServicesIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteContactRoute: SiteContactRoute,
  SiteTalentStaffingRoute: SiteTalentStaffingRoute,
  SiteTrainingRoute: SiteTrainingRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteCoursesSlugRoute: SiteCoursesSlugRoute,
  SiteExpertiseSlugRoute: SiteExpertiseSlugRoute,
  SiteServicesSlugRoute: SiteServicesSlugRoute,
  SiteCoursesIndexRoute: SiteCoursesIndexRoute,
  SiteExpertiseIndexRoute: SiteExpertiseIndexRoute,
  SiteServicesIndexRoute: SiteServicesIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
